version: '3'
services:
  web:
    image: fpfis/httpd-php-dev:{{ salt['pillar.get']('docker:php_version','5.6') }}
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
    environment:
      - DOCUMENT_ROOT=${PWD}/build
      - XDEBUG_CONFIG=idekey=cloud9ide remote_connect_back=0 remote_host=${DOCKER_HOST_IP} remote_enable=1
    depends_on:
      - mysql
    ports:
      - 8080:8080
  mysql:
    image: fpfis/mysql{{ salt['pillar.get']('docker:mysql_version','56') }}